language: bash
sudo: enabled
dist: trusty

git:
  depth: 1

script:
  - sudo apt-get update
  - sudo apt-get --assume-yes install make git-core cmake
  - export VITASDK=/usr/local/vitasdk && export PATH=$VITASDK/bin:$PATH
  - git clone https://github.com/vitasdk/vdpm
  - cd vdpm
  - ./bootstrap-vitasdk.sh
  - sudo ./install-all.sh
  - vitasdk-update
  - cd ..
  - mkdir -p skprx/build && mkdir -p vpk/build
  - cd skprx/build && cmake ..
  - make
  - cd ../../
  - cd vpk/build && cmake ..
  - make